"""DIMER inference package for the pinned ``google/owlvit-base-patch32`` checkpoint."""

from .pipeline import (
    DEFAULT_WEIGHTS_DIR,
    DETECTION_THRESHOLD,
    INPUT_SCHEMA,
    MAX_DETECTIONS,
    MAX_IMAGE_SIDE,
    MAX_PROMPT_CHARS,
    MAX_PROMPTS,
    MAX_TEXT_TOKENS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    OwlViTDetectionPipeline,
    box_iou,
    evaluation_report,
    format_prompts,
    is_pinned,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DEFAULT_WEIGHTS_DIR",
    "DETECTION_THRESHOLD",
    "INPUT_SCHEMA",
    "MAX_DETECTIONS",
    "MAX_IMAGE_SIDE",
    "MAX_PROMPTS",
    "MAX_PROMPT_CHARS",
    "MAX_TEXT_TOKENS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "OwlViTDetectionPipeline",
    "box_iou",
    "is_pinned",
    "evaluation_report",
    "format_prompts",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
